### Import Check ⬇️

In [1]:
# Import Check
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

print("Alle Pakete erfolgreich geladen ✅")

Alle Pakete erfolgreich geladen ✅

### ROM-Struktur verstehen, welche Version ist vorhanden? ⬇️

In [2]:
ROM_PATH = "../data/pokemon_firered.gba"

with open(ROM_PATH, "rb") as f:
    header = f.read(0xC0)

game_code = header[0xAC:0xB0].decode("ascii")
game_title = header[0xA0:0xAC].decode("ascii").strip()

print(f"Spieltitel: {game_title}")
print(f"Game Code:  {game_code}")

Spieltitel: POKEMON FIRE
Game Code:  BPRD

### Pokemon Zeichenkodierung Hexa nicht Standard: Quelle -> Claude.ai ⬇️

In [3]:
CHAR_MAP = {
    0xBB: "A", 0xBC: "B", 0xBD: "C", 0xBE: "D", 0xBF: "E",
    0xC0: "F", 0xC1: "G", 0xC2: "H", 0xC3: "I", 0xC4: "J",
    0xC5: "K", 0xC6: "L", 0xC7: "M", 0xC8: "N", 0xC9: "O",
    0xCA: "P", 0xCB: "Q", 0xCC: "R", 0xCD: "S", 0xCE: "T",
    0xCF: "U", 0xD0: "V", 0xD1: "W", 0xD2: "X", 0xD3: "Y",
    0xD4: "Z",
    0xD5: "a", 0xD6: "b", 0xD7: "c", 0xD8: "d", 0xD9: "e",
    0xDA: "f", 0xDB: "g", 0xDC: "h", 0xDD: "i", 0xDE: "j",
    0xDF: "k", 0xE0: "l", 0xE1: "m", 0xE2: "n", 0xE3: "o",
    0xE4: "p", 0xE5: "q", 0xE6: "r", 0xE7: "s", 0xE8: "t",
    0xE9: "u", 0xEA: "v", 0xEB: "w", 0xEC: "x", 0xED: "y",
    0xEE: "z",
    0x00: " ", 0xFF: ""  # Leerzeichen & String-Ende
}

### Offset Testausgabe aller Pokemon mit 10 Byte Abstand ⬇️

In [4]:
def decode_pokemon_string(data):
    result = ""
    for byte in data:
        if byte == 0xFF:  # String-Ende
            break
        result += CHAR_MAP.get(byte, "?")
    return result.strip()

# Anpassbare Variablen festlegen und Namen auslesen
NAMES_OFFSET = 0x245EE0
POKEMON_COUNT = 151
NAME_LENGTH = 10

pokemon_namen = []

with open("../data/pokemon_firered.gba", "rb") as f:
    for i in range(POKEMON_COUNT):
        offset = NAMES_OFFSET + (i * NAME_LENGTH)
        f.seek(offset)
        name_bytes = f.read(NAME_LENGTH)
        name = decode_pokemon_string(name_bytes)
        pokemon_namen.append({"id": i + 1, "name": name})

for p in pokemon_namen:
    print(f"#{p['id']:03d} {p['name']}")

#001 SANDAM
#002 ER
#003 AN?
#004 RINA
#005 OQUEEN
#006 DORAN?
#007 IDORINO
#008 NIDOKING
#009 PIEPI
#010 PIXI
#011 VULPIX
#012 VULNON
#013 A
#014 LUFF
#015 DELUFF
#016 AT
#017 LBAT
#018 YRAPLA
#019 DUFLOR
#020 GIFLOR
#021 PARAS
#022 PARASEK
#023
#024
#025 DIGD
#026 A
#027 DRI
#028 UZI
#029 NOBILIKAT
#030 ENTON
#031 ENTORON
#032 MENKI
#033 RASAFF
#034 FUKANO
#035
#036 I
#037 SEL
#038 PUTZI
#039 APPO
#040 BRA
#041 KADABRA
#042 SIMSALA
#043 MACHOLLO
#044
#045 K
#046 EI
#047 NSA
#048 IGARIA
#049 ZENIA
#050 NTACHA
#051 ENTOXA
#052 KLEINSTEIN
#053
#054 GEOWAZ
#055 PONITA
#056 GALLOP
#057 A
#058 ON
#059 US
#060 NETILO
#061 GNETON
#062 ORENTA
#063 DODU
#064 DODRI
#065 JUROB
#066 JUGONG
#067 SLEIMA
#068
#069 OK
#070 HAS
#071 TOS
#072 BULAK
#073 LPOLLO
#074 GENGAR
#075 ONIX
#076 TRAUMATO
#077
#078 KRABBY
#079
#080 ER
#081 OBAL
#082 TROBAL
#083 EI
#084 OKOWEI
#085 TRAGOSSO
#086 KNOGGA
#087 KICKLEE
#088 NOCKCHA
#089 N
#090 P
#091 N
#092 MOG
#093 ORN
#094 ZEROS
#095 HANEIRA
#096 TANGELA
#097 KANGAMA
#098 SEEPER
#099 SEEMON
#100 GOLDIN
#101 I
#102 NG
#103 NDU
#104 RMIE
#105 NTIMOS
#106 ICHLOR
#107 ROSSANA
#108 ELEKTEK
#109 MAGMAR
#110 PINSIR
#111 TAUROS
#112
#113 DOR
#114 DOS
#115 RAS
#116 TTO
#117 VOLI
#118 AQUANA
#119 BLITZA
#120 FLAMARA
#121 PORYGON
#122
#123 AS
#124 SO
#125 TO
#126 UTOPS
#127 RODACTYL
#128 ELAXO
#129 ARKTOS
#130 ZAPDOS
#131 LAVADOS
#132 DRATINI
#133
#134 IR
#135 RAN
#136 U
#137
#138 DIVIE
#139 ORBLATT
#140 MEGANIE
#141 FEURIGEL
#142 IGELAVAR
#143
#144 O
#145 ANI
#146 ROC
#147 RGATOR
#148 SOR
#149 ESENIOR
#150 OOTHOOT
#151 NOCTUH

### Offensichtlich falscher Offset in vorheriger Zelle
### Suche nach "BISASAM" (Pokemon 001)
### In Pokemon-Kodierung übersetzen ⬇️

In [5]:
CHAR_MAP_REVERSE = {v: k for k, v in CHAR_MAP.items()}

def encode_pokemon_string(text):
    return bytes([CHAR_MAP_REVERSE.get(c, 0x00) for c in text])

# Nach "BISASAM" in der ROM suchen
search = encode_pokemon_string("BISASAM")
print(f"Suche nach Byte: {search.hex()}")

with open("../data/pokemon_firered.gba", "rb") as f:
    rom_data = f.read()

position = rom_data.find(search)
print(f"Gefunden an Position: {hex(position)}")

# Neuer Offset = Position von BISASAM
# (da BISASAM Pokémon #001 ist, ist das direkt der Basis-Offset)
print(f"Neuer NAMES_OFFSET: {hex(position)}")

Suche nach Byte: bcc3cdbbcdbbc7
Gefunden an Position: 0x1907b7
Neuer NAMES_OFFSET: 0x1907b7

### Neuen Offset testen ⬇️

In [6]:
NAMES_OFFSET = 0x1907b7
POKEMON_COUNT = 151
NAME_LENGTH = 10

pokemon_namen = []

with open("../data/pokemon_firered.gba", "rb") as f:
    for i in range(POKEMON_COUNT):
        offset = NAMES_OFFSET + (i * NAME_LENGTH)
        f.seek(offset)
        name_bytes = f.read(NAME_LENGTH)
        name = decode_pokemon_string(name_bytes)
        pokemon_namen.append({"id": i + 1, "name": name})

for p in pokemon_namen:
    print(f"#{p['id']:03d} {p['name']}")

#001 BISASAM so
#002 ll es sein
#003 ??Es ist l
#004 eicht zu t
#005 rainieren?
#006 ???? du m?
#007 chtest als
#008 o das?PFLA
#009 NZEN?POK?M
#010 ON BISASAM
#011 ?
#012 OK?MON ist
#013 wirklich?
#014 energiegel
#015 aden?
#016 rh?lt????
#017 PROF? EICH
#018 ? Wenn du
#019 auf ein wi
#020 ldes?POK?M
#021 ON triffst
#022 ? dann kan
#023 n dein?POK
#024 ?MON dageg
#025 en k?mpfen
#026 ?
#027 CH? ??? we
#028 nn du dein
#029 ?POK?MON k
#030 ?mpfen l?s
#031 st? wird e
#032 s?st?rker?
#033
#034 H? Hallo?
#035 ????Wie ge
#036 ht es dem
#037 POK?MON??E
#038 s scheint
#039 dich sehr
#040 zu m?gen??
#041 Du musst a
#042 ls POK?MON
#043 TRAINER s
#044 ehr?talent
#045 iert sein?
#046 ?Du hast e
#047 twas f?r m
#048 ich?
#049 ergibt?PRO
#050 F? EICH da
#051 s PAKET?
#052 h? Auf die
#053 sen SPEZIA
#054 L?POK?BALL
#055 ?warte ich
#056 schon lan
#057 ge? ?Viele
#058 n Dank?
#059 OF? EICH?
#060 Ach ja? Ic
#061 h habe ein
#062 e?gro?e Au
#063 fgabe f?r
#064 euch?
#065 dem Tisch
#066 dort seht
#067 ihr eine?E
#068 rfindung v
#069 on mir? de
#070 n POK?DEX?
#071 ?Er erfass
#072 t automati
#073 sch Daten
#074 ?ber?POK?M
#075 ON? die ma
#076 n gefangen
#077 oder?gese
#078 hen hat??E
#079 r ist eine
#080 Art Hi?Te
#081 ch?Lexikon
#082 ?
#083 CH? ??? ??
#084 ??Diese be
#085 iden sind
#086 f?r euch?
#087 ?? erh?lt
#088 einen POK?
#089 DEX von?PR
#090 OF? EICH?
#091 PROF? EICH
#092 ? Es reich
#093 t nicht? ?
#094 POK?MON zu
#095 sehen? um
#096 detaillie
#097 rte?Inform
#098 ationen ?b
#099 er sie zu
#100 sammeln??D
#101 u musst si
#102 e fangen?
#103 Benutze da
#104 s?hier? um
#105 wilde POK
#106 ?MON?einzu
#107 fangen?
#108 erh?lt?f?
#109 nf POK?B?L
#110 LE?
#111 ein wilde
#112 s POK?MON
#113 auf? so?ka
#114 nnst du es
#115 fangen??W
#116 irf einfac
#117 h einen PO
#118 K?BALL und
#119 ?versuche
#120 es??Doch d
#121 u wirst of
#122 tmals kein
#123 en Erfolg?
#124 haben??Ein
#125 gesundes
#126 POK?MON en
#127 tkommt?sch
#128 nell? Man
#129 muss schon
#130 etwas?Gl?
#131 ck haben?
#132 Ein Lexiko
#133 n ?ber all
#134 e POK?MON
#135 der?Welt??
#136 ??Das war
#137 immer mein
#138 Traum??Ab
#139 er ich bin
#140 zu alt??I
#141 ch schaffe
#142 es nicht
#143 mehr??Also
#144 bitte ich
#145 euch? mei
#146 nen Traum?
#147 zu verwirk
#148 lichen??Ma
#149 cht euch a
#150 uf den Weg
#151 ??Dies ist

### Falscher Offset mit "BISASAM", wahrscheinlich einfach nur Storytext
### Suche eingrenzen mit "BISASAM" und "BISAKNOSP" ⬇️

In [7]:
search1 = encode_pokemon_string("BISASAM")
search2 = encode_pokemon_string("BISAKNOSP")

with open("../data/pokemon_firered.gba", "rb") as f:
    rom_data = f.read()

# Alle Vorkommen von BISASAM finden
pos = 0
while True:
    position = rom_data.find(search1, pos)
    if position == -1:
        break

    # Prüfen ob BISAKNOSP genau 10 Bytes später kommt
    next_pos = position + 10
    if rom_data[next_pos:next_pos + len(search2)] == search2:
        print(f"✅ Namenstabelle gefunden bei: {hex(position)}")
        break
    else:
        print(f"❌ Falscher Treffer bei: {hex(position)}")

    pos = position + 1

❌ Falscher Treffer bei: 0x1907b7
❌ Falscher Treffer bei: 0x190814
❌ Falscher Treffer bei: 0x245dbb

### Falsche Treffer in Zelle zuvor.
### Prüfen was 10 Byte später steht.
### Vielleicht doch anderer Byte Absatnd? ⬇️

In [8]:
search1 = encode_pokemon_string("BISASAM")

with open("../data/pokemon_firered.gba", "rb") as f:
    rom_data = f.read()

pos = 0
while True:
    position = rom_data.find(search1, pos)
    if position == -1:
        break

    # Zeige was nach BISASAM kommt (20 Bytes)
    after = rom_data[position:position + 30]
    decoded = decode_pokemon_string(after)

    print(f"Position {hex(position)}: '{decoded}'")
    print(f"  Raw Bytes: {after.hex()}")
    print()

    pos = position + 1

Position 0x1907b7: 'BISASAM soll es sein??Es ist l'
  Raw Bytes: bcc3cdbbcdbbc700e7e3e0e000d9e700e7d9dde2abfebfe700dde7e800e0

Position 0x190814: 'BISASAM?'
  Raw Bytes: bcc3cdbbcdbbc7acffbeddd9e7d9e700cac9c51bc7c9c800dde7e800ebdd

Position 0x245dbb: 'BISASAM'
  Raw Bytes: bcc3cdbbcdbbc7ff000000bcc3cdbbc5c8c9cdcaff00bcc3cdbbc0c6c9cc

### Position 0x245dbb: 'BISASAM' sieht vielversprechend aus ff = String Ende dann 3 Nullbyte Abstand
### bcc3cdbbcdbbc7ff000000 = (B I S A S A M = 7 Byte) + (ff = 1 Byte) + (00 00 00 = 3 Byte) also 7+1+3=11 Byte
### Gegentest: bcc3cdbbc5c8c9cdcaff00 = (B I S A K N O S P = 9 Byte) + (ff = 1 Byte) + (00 = 1 Byte) also 9+1+1=11 Byte
### Es sind nicht 10 Byte Abstand sondern 11
### Offset Test mit neuen Erkenntnissen ⬇️

In [9]:
NAMES_OFFSET = 0x245dbb
POKEMON_COUNT = 151
NAME_LENGTH = 11  # ← geändert!

pokemon_namen = []

with open("../data/pokemon_firered.gba", "rb") as f:
    for i in range(POKEMON_COUNT):
        offset = NAMES_OFFSET + (i * NAME_LENGTH)
        f.seek(offset)
        name_bytes = f.read(NAME_LENGTH)
        name = decode_pokemon_string(name_bytes)
        pokemon_namen.append({"id": i + 1, "name": name})

df_namen = pd.DataFrame(pokemon_namen)
df_namen

      id       name
0      1    BISASAM
1      2  BISAKNOSP
2      3   BISAFLOR
3      4   GLUMANDA
4      5    GLUTEXO
..   ...        ...
146  147    DRATINI
147  148   DRAGONIR
148  149   DRAGORAN
149  150      MEWTU
150  151        MEW

[151 rows x 2 columns]

### Offset für Pokenamen richtig identifiziert
### Jetzt Basiswerte also HP, ATK, DEF, Speed, SP.ATK, SP.DEF (45, 49, 49, 45, 65, 65) extrahieren ⬇️

In [10]:
import struct
bisasam_stats = bytes([45, 49, 49, 45, 65, 65])

with open("../data/pokemon_firered.gba", "rb") as f:
    rom_data = f.read()

pos = 0
while True:
    position = rom_data.find(bisasam_stats, pos)
    if position == -1:
        print("Nichts weiter gefunden!")
        break

    print(f"Treffer bei: {hex(position)}")
    print(f"Raw Bytes: {rom_data[position:position+28].hex()}")
    print()

    pos = position + 1

Treffer bei: 0x2546c4
Raw Bytes: 2d31312d41410c032d400001000000001f1446030107410000030000

Nichts weiter gefunden!

### Mit aller Wahrscheinlichkeit Treffer
### 2d 31 31 2d 41 41 = sind Bisasams Werte (45 49 49 45 65 65)
### Alle stats bei allen Pokemon auslesen ⬇️

In [14]:
STATS_OFFSET = 0x2546c4
POKEMON_COUNT = 151

pokemon_stats = []

with open("../data/pokemon_firered.gba", "rb") as f:
    for i in range(POKEMON_COUNT):
        offset = STATS_OFFSET + (i * 28)
        f.seek(offset)
        data = f.read(28)

        stats = struct.unpack_from("BBBBBB", data, 0)

        pokemon_stats.append({
            "hp":             stats[0],
            "angriff":        stats[1],
            "verteidigung":   stats[2],
            "speed":          stats[3],
            "sp_angriff":     stats[4],
            "sp_verteidigung":stats[5],
        })

df_stats = pd.DataFrame(pokemon_stats)
pd.set_option('display.max_rows', None)  # Alle Zeilen anzeigen
df_stats

      hp  angriff  verteidigung  speed  sp_angriff  sp_verteidigung
0     45       49            49     45          65               65
1     60       62            63     60          80               80
2     80       82            83     80         100              100
3     39       52            43     65          60               50
4     58       64            58     80          80               65
5     78       84            78    100         109               85
6     44       48            65     43          50               64
7     59       63            80     58          65               80
8     79       83           100     78          85              105
9     45       30            35     45          20               20
10    50       20            55     30          25               25
11    60       45            50     70          80               80
12    40       35            30     50          20               20
13    45       25            50     35          25               25
14    65       80            40     75          45               80
15    40       45            40     56          35               35
16    63       60            55     71          50               50
17    83       80            75     91          70               70
18    30       56            35     72          25               35
19    55       81            60     97          50               70
20    40       60            30     70          31               31
21    65       90            65    100          61               61
22    35       60            44     55          40               54
23    60       85            69     80          65               79
24    35       55            30     90          50               40
25    60       90            55    100          90               80
26    50       75            85     40          20               30
27    75      100           110     65          45               55
28    55       47            52     41          40               40
29    70       62            67     56          55               55
30    90       82            87     76          75               85
31    46       57            40     50          40               40
32    61       72            57     65          55               55
33    81       92            77     85          85               75
34    70       45            48     35          60               65
35    95       70            73     60          85               90
36    38       41            40     65          50               65
37    73       76            75    100          81              100
38   115       45            20     20          45               25
39   140       70            45     45          75               50
40    40       45            35     55          30               40
41    75       80            70     90          65               75
42    45       50            55     30          75               65
43    60       65            70     40          85               75
44    75       80            85     50         100               90
45    35       70            55     25          45               55
46    60       95            80     30          60               80
47    60       55            50     45          40               55
48    70       65            60     90          90               75
49    10       55            25     95          35               45
50    35       80            50    120          50               70
51    40       45            35     90          40               40
52    65       70            60    115          65               65
53    50       52            48     55          65               50
54    80       82            78     85          95               80
55    40       80            35     70          35               45
56    65      105            60     95          60               70
57    55       70            45     60          70               50
58    90      110            80     95         100               80
59    40       50            40     90          40               40
60    65       65            65     90          50               50
61    90       85            95     70          70               90
62    25       20            15     90         105               55
63    40       35            30    105         120               70
64    55       50            45    120         135               85
65    70       80            50     35          35               35
66    80      100            70     45          50               60
67    90      130            80     55          65               85
68    50       75            35     40          70               30
69    65       90            50     55          85               45
70    80      105            65     70         100               60
71    40       40            35     70          50              100
72    80       70            65    100          80              120
73    40       80           100     20          30               30
74    55       95           115     35          45               45
75    80      110           130     45          55               65
76    50       85            55     90          65               65
77    65      100            70    105          80               80
78    90       65            65     15          40               40
79    95       75           110     30         100               80
80    25       35            70     45          95               55
81    50       60            95     70         120               70
82    52       65            55     60          58               62
83    35       85            45     75          35               35
84    60      110            70    100          60               60
85    65       45            55     45          45               70
86    90       70            80     70          70               95
87    80       80            50     25          40               50
88   105      105            75     50          65              100
89    30       65           100     40          45               25
90    50       95           180     70          85               45
91    30       35            30     80         100               35
92    45       50            45     95         115               55
93    60       65            60    110         130               75
94    35       45           160     70          30               45
95    60       48            45     42          43               90
96    85       73            70     67          73              115
97    30      105            90     50          25               25
98    55      130           115     75          50               50
99    40       30            50    100          55               55
100   60       50            70    140          80               80
101   60       40            80     40          60               45
102   95       95            85     55         125               65
103   50       50            95     35          40               50
104   60       80           110     45          50               80
105   50      120            53     87          35              110
106   50      105            79     76          35              110
107   90       55            75     30          60               75
108   40       65            95     35          60               45
109   65       90           120     60          85               70
110   80       85            95     25          30               30
111  105      130           120     40          45               45
112  250        5             5     50          35              105
113   65       55           115     60         100               40
114  105       95            80     90          40               80
115   30       40            70     60          70               25
116   55       65            95     85          95               45
117   45       67            60     63          35               50
118   80       92            65     68          65               80
119   30       45            55     85          70               55
120   60       75            85    115         100               85
121   40       45            65     90         100              120
122   70      110            80    105          55               80
123   65       50            35     95         115               95
124   65       83            57    105          95               85
125   65       95            57     93         100               85
126   65      125           100     85          55               70
127   75      100            95    110          40               70
128   20       10            55     80          15               20
129   95      125            79     81          60              100
130  130       85            80     60          85               95
131   48       48            48     48          48               48
132   55       55            50     55          45               65
133  130       65            60     65         110               95
134   65       65            60    130         110               95
135   65      130            60     65          95              110
136   65       60            70     40          85               75
137   35       40           100     35          90               55
138   70       60           125     55         115               70
139   30       80            90     55          55               45
140   60      115           105     80          65               70
141   80      105            65    130          60               75
142  160      110            65     30          65              110
143   90       85           100     85          95              125
144   90       90            85    100         125               90
145   90      100            90     90         125               85
146   41       64            45     50          50               50
147   61       84            65     70          70               70
148   91      134            95     80         100              100
149  106      110            90    130         154               90
150  100      100           100    100         100              100

In [12]:
# Typ-ID
TYPES = {
    0:  "Normal",  1:  "Kampf",   2:  "Flug",
    3:  "Gift",    4:  "Boden",   5:  "Gestein",
    6:  "Käfer",   7:  "Geist",   8:  "Stahl",
    10: "Feuer",   11: "Wasser",  12: "Gras",
    13: "Elektro", 14: "Psycho",  15: "Eis",
    16: "Drache",  17: "Unlicht"
}

pokemon_typen = []

with open("../data/pokemon_firered.gba", "rb") as f:
    for i in range(POKEMON_COUNT):
        offset = STATS_OFFSET + (i * 28)
        f.seek(offset)
        data = f.read(28)

        stats = struct.unpack_from("BBBBBBBB", data, 0)

        pokemon_typen.append({
            "typ1": TYPES.get(stats[6], f"Unbekannt({stats[6]})"),
            "typ2": TYPES.get(stats[7], f"Unbekannt({stats[7]})")
        })

df_typen = pd.DataFrame(pokemon_typen)
df_typen

        typ1     typ2
0       Gras     Gift
1       Gras     Gift
2       Gras     Gift
3      Feuer    Feuer
4      Feuer    Feuer
5      Feuer     Flug
6     Wasser   Wasser
7     Wasser   Wasser
8     Wasser   Wasser
9      Käfer    Käfer
10     Käfer    Käfer
11     Käfer     Flug
12     Käfer     Gift
13     Käfer     Gift
14     Käfer     Gift
15    Normal     Flug
16    Normal     Flug
17    Normal     Flug
18    Normal   Normal
19    Normal   Normal
20    Normal     Flug
21    Normal     Flug
22      Gift     Gift
23      Gift     Gift
24   Elektro  Elektro
25   Elektro  Elektro
26     Boden    Boden
27     Boden    Boden
28      Gift     Gift
29      Gift     Gift
30      Gift    Boden
31      Gift     Gift
32      Gift     Gift
33      Gift    Boden
34    Normal   Normal
35    Normal   Normal
36     Feuer    Feuer
37     Feuer    Feuer
38    Normal   Normal
39    Normal   Normal
40      Gift     Flug
41      Gift     Flug
42      Gras     Gift
43      Gras     Gift
44      Gras     Gift
45     Käfer     Gras
46     Käfer     Gras
47     Käfer     Gift
48     Käfer     Gift
49     Boden    Boden
50     Boden    Boden
51    Normal   Normal
52    Normal   Normal
53    Wasser   Wasser
54    Wasser   Wasser
55     Kampf    Kampf
56     Kampf    Kampf
57     Feuer    Feuer
58     Feuer    Feuer
59    Wasser   Wasser
60    Wasser   Wasser
61    Wasser    Kampf
62    Psycho   Psycho
63    Psycho   Psycho
64    Psycho   Psycho
65     Kampf    Kampf
66     Kampf    Kampf
67     Kampf    Kampf
68      Gras     Gift
69      Gras     Gift
70      Gras     Gift
71    Wasser     Gift
72    Wasser     Gift
73   Gestein    Boden
74   Gestein    Boden
75   Gestein    Boden
76     Feuer    Feuer
77     Feuer    Feuer
78    Wasser   Psycho
79    Wasser   Psycho
80   Elektro    Stahl
81   Elektro    Stahl
82    Normal     Flug
83    Normal     Flug
84    Normal     Flug
85    Wasser   Wasser
86    Wasser      Eis
87      Gift     Gift
88      Gift     Gift
89    Wasser   Wasser
90    Wasser      Eis
91     Geist     Gift
92     Geist     Gift
93     Geist     Gift
94   Gestein    Boden
95    Psycho   Psycho
96    Psycho   Psycho
97    Wasser   Wasser
98    Wasser   Wasser
99   Elektro  Elektro
100  Elektro  Elektro
101     Gras   Psycho
102     Gras   Psycho
103    Boden    Boden
104    Boden    Boden
105    Kampf    Kampf
106    Kampf    Kampf
107   Normal   Normal
108     Gift     Gift
109     Gift     Gift
110    Boden  Gestein
111    Boden  Gestein
112   Normal   Normal
113     Gras     Gras
114   Normal   Normal
115   Wasser   Wasser
116   Wasser   Wasser
117   Wasser   Wasser
118   Wasser   Wasser
119   Wasser   Wasser
120   Wasser   Psycho
121   Psycho   Psycho
122    Käfer     Flug
123      Eis   Psycho
124  Elektro  Elektro
125    Feuer    Feuer
126    Käfer    Käfer
127   Normal   Normal
128   Wasser   Wasser
129   Wasser     Flug
130   Wasser      Eis
131   Normal   Normal
132   Normal   Normal
133   Wasser   Wasser
134  Elektro  Elektro
135    Feuer    Feuer
136   Normal   Normal
137  Gestein   Wasser
138  Gestein   Wasser
139  Gestein   Wasser
140  Gestein   Wasser
141  Gestein     Flug
142   Normal   Normal
143      Eis     Flug
144  Elektro     Flug
145    Feuer     Flug
146   Drache   Drache
147   Drache   Drache
148   Drache     Flug
149   Psycho   Psycho
150   Psycho   Psycho

### Stats ausgelesen
### Typen sollten im selben Byte-Block sein direkt hinter den stats (Check = Bisasam 001/00 sollte Gras/Gift sein) ⬇️

### Typen wurden erfolgreich extrahiert
### Jetzt Zusammenführung von drei df zu einem df (pd.concat weil alle df gleich viele Zeilen, Reihenfolge) ⬇️

In [15]:
df_pokemon = pd.concat([df_namen, df_stats, df_typen], axis=1)

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
df_pokemon = df_pokemon.set_index("id")
df_pokemon

,name,hp,angriff,verteidigung,speed,sp_angriff,sp_verteidigung,typ1,typ2
id,,,,,,,,,
1,BISASAM,45,49,49,45,65,65,Gras,Gift
2,BISAKNOSP,60,62,63,60,80,80,Gras,Gift
3,BISAFLOR,80,82,83,80,100,100,Gras,Gift
4,GLUMANDA,39,52,43,65,60,50,Feuer,Feuer
5,GLUTEXO,58,64,58,80,80,65,Feuer,Feuer
6,GLURAK,78,84,78,100,109,85,Feuer,Flug
7,SCHIGGY,44,48,65,43,50,64,Wasser,Wasser
8,SCHILLOK,59,63,80,58,65,80,Wasser,Wasser
9,TURTOK,79,83,100,78,85,105,Wasser,Wasser
10,RAUPY,45,30,35,45,20,20,Käfer,Käfer
11,SAFCON,50,20,55,30,25,25,Käfer,Käfer
12,SMETTBO,60,45,50,70,80,80,Käfer,Flug
13,HORNLIU,40,35,30,50,20,20,Käfer,Gift
14,KOKUNA,45,25,50,35,25,25,Käfer,Gift
15,BIBOR,65,80,40,75,45,80,Käfer,Gift
16,TAUBSI,40,45,40,56,35,35,Normal,Flug
17,TAUBOGA,63,60,55,71,50,50,Normal,Flug
18,TAUBOSS,83,80,75,91,70,70,Normal,Flug
19,RATTFRATZ,30,56,35,72,25,35,Normal,Normal
20,RATTIKARL,55,81,60,97,50,70,Normal,Normal
21,HABITAK,40,60,30,70,31,31,Normal,Flug
22,IBITAK,65,90,65,100,61,61,Normal,Flug
23,RETTAN,35,60,44,55,40,54,Gift,Gift
24,ARBOK,60,85,69,80,65,79,Gift,Gift
25,PIKACHU,35,55,30,90,50,40,Elektro,Elektro
26,RAICHU,60,90,55,100,90,80,Elektro,Elektro
27,SANDAN,50,75,85,40,20,30,Boden,Boden
28,SANDAMER,75,100,110,65,45,55,Boden,Boden
29,NIDORAN?,55,47,52,41,40,40,Gift,Gift
30,NIDORINA,70,62,67,56,55,55,Gift,Gift
31,NIDOQUEEN,90,82,87,76,75,85,Gift,Boden
32,NIDORAN?,46,57,40,50,40,40,Gift,Gift
33,NIDORINO,61,72,57,65,55,55,Gift,Gift
34,NIDOKING,81,92,77,85,85,75,Gift,Boden
35,PIEPI,70,45,48,35,60,65,Normal,Normal
36,PIXI,95,70,73,60,85,90,Normal,Normal
37,VULPIX,38,41,40,65,50,65,Feuer,Feuer
38,VULNONA,73,76,75,100,81,100,Feuer,Feuer
39,PUMMELUFF,115,45,20,20,45,25,Normal,Normal
40,KNUDDELUFF,140,70,45,45,75,50,Normal,Normal
41,ZUBAT,40,45,35,55,30,40,Gift,Flug
42,GOLBAT,75,80,70,90,65,75,Gift,Flug
43,MYRAPLA,45,50,55,30,75,65,Gras,Gift
44,DUFLOR,60,65,70,40,85,75,Gras,Gift
45,GIFLOR,75,80,85,50,100,90,Gras,Gift
46,PARAS,35,70,55,25,45,55,Käfer,Gras
47,PARASEK,60,95,80,30,60,80,Käfer,Gras
48,BLUZUK,60,55,50,45,40,55,Käfer,Gift
49,OMOT,70,65,60,90,90,75,Käfer,Gift
50,DIGDA,10,55,25,95,35,45,Boden,Boden
51,DIGDRI,35,80,50,120,50,70,Boden,Boden
52,MAUZI,40,45,35,90,40,40,Normal,Normal
53,SNOBILIKAT,65,70,60,115,65,65,Normal,Normal
54,ENTON,50,52,48,55,65,50,Wasser,Wasser
55,ENTORON,80,82,78,85,95,80,Wasser,Wasser
56,MENKI,40,80,35,70,35,45,Kampf,Kampf
57,RASAFF,65,105,60,95,60,70,Kampf,Kampf
58,FUKANO,55,70,45,60,70,50,Feuer,Feuer
59,ARKANI,90,110,80,95,100,80,Feuer,Feuer
60,QUAPSEL,40,50,40,90,40,40,Wasser,Wasser
61,QUAPUTZI,65,65,65,90,50,50,Wasser,Wasser
62,QUAPPO,90,85,95,70,70,90,Wasser,Kampf
63,ABRA,25,20,15,90,105,55,Psycho,Psycho
64,KADABRA,40,35,30,105,120,70,Psycho,Psycho
65,SIMSALA,55,50,45,120,135,85,Psycho,Psycho
66,MACHOLLO,70,80,50,35,35,35,Kampf,Kampf
67,MASCHOCK,80,100,70,45,50,60,Kampf,Kampf
68,MACHOMEI,90,130,80,55,65,85,Kampf,Kampf
69,KNOFENSA,50,75,35,40,70,30,Gras,Gift
70,ULTRIGARIA,65,90,50,55,85,45,Gras,Gift
71,SARZENIA,80,105,65,70,100,60,Gras,Gift
72,TENTACHA,40,40,35,70,50,100,Wasser,Gift
73,TENTOXA,80,70,65,100,80,120,Wasser,Gift
74,KLEINSTEIN,40,80,100,20,30,30,Gestein,Boden
75,GEOROK,55,95,115,35,45,45,Gestein,Boden
76,GEOWAZ,80,110,130,45,55,65,Gestein,Boden
77,PONITA,50,85,55,90,65,65,Feuer,Feuer
78,GALLOPA,65,100,70,105,80,80,Feuer,Feuer
79,FLEGMON,90,65,65,15,40,40,Wasser,Psycho
80,LAHMUS,95,75,110,30,100,80,Wasser,Psycho
81,MAGNETILO,25,35,70,45,95,55,Elektro,Stahl
82,MAGNETON,50,60,95,70,120,70,Elektro,Stahl
83,PORENTA,52,65,55,60,58,62,Normal,Flug
84,DODU,35,85,45,75,35,35,Normal,Flug
85,DODRI,60,110,70,100,60,60,Normal,Flug
86,JUROB,65,45,55,45,45,70,Wasser,Wasser
87,JUGONG,90,70,80,70,70,95,Wasser,Eis
88,SLEIMA,80,80,50,25,40,50,Gift,Gift
89,SLEIMOK,105,105,75,50,65,100,Gift,Gift
90,MUSCHAS,30,65,100,40,45,25,Wasser,Wasser
91,AUSTOS,50,95,180,70,85,45,Wasser,Eis
92,NEBULAK,30,35,30,80,100,35,Geist,Gift
93,ALPOLLO,45,50,45,95,115,55,Geist,Gift
94,GENGAR,60,65,60,110,130,75,Geist,Gift
95,ONIX,35,45,160,70,30,45,Gestein,Boden
96,TRAUMATO,60,48,45,42,43,90,Psycho,Psycho
97,HYPNO,85,73,70,67,73,115,Psycho,Psycho
98,KRABBY,30,105,90,50,25,25,Wasser,Wasser
99,KINGLER,55,130,115,75,50,50,Wasser,Wasser
100,VOLTOBAL,40,30,50,100,55,55,Elektro,Elektro
101,LEKTROBAL,60,50,70,140,80,80,Elektro,Elektro
102,OWEI,60,40,80,40,60,45,Gras,Psycho
103,KOKOWEI,95,95,85,55,125,65,Gras,Psycho
104,TRAGOSSO,50,50,95,35,40,50,Boden,Boden
105,KNOGGA,60,80,110,45,50,80,Boden,Boden
106,KICKLEE,50,120,53,87,35,110,Kampf,Kampf
107,NOCKCHAN,50,105,79,76,35,110,Kampf,Kampf
108,SCHLURP,90,55,75,30,60,75,Normal,Normal
109,SMOGON,40,65,95,35,60,45,Gift,Gift
110,SMOGMOG,65,90,120,60,85,70,Gift,Gift
111,RIHORN,80,85,95,25,30,30,Boden,Gestein
112,RIZEROS,105,130,120,40,45,45,Boden,Gestein
113,CHANEIRA,250,5,5,50,35,105,Normal,Normal
114,TANGELA,65,55,115,60,100,40,Gras,Gras
115,KANGAMA,105,95,80,90,40,80,Normal,Normal
116,SEEPER,30,40,70,60,70,25,Wasser,Wasser
117,SEEMON,55,65,95,85,95,45,Wasser,Wasser
118,GOLDINI,45,67,60,63,35,50,Wasser,Wasser
119,GOLKING,80,92,65,68,65,80,Wasser,Wasser
120,STERNDU,30,45,55,85,70,55,Wasser,Wasser
121,STARMIE,60,75,85,115,100,85,Wasser,Psycho
122,PANTIMOS,40,45,65,90,100,120,Psycho,Psycho
123,SICHLOR,70,110,80,105,55,80,Käfer,Flug
124,ROSSANA,65,50,35,95,115,95,Eis,Psycho
125,ELEKTEK,65,83,57,105,95,85,Elektro,Elektro
126,MAGMAR,65,95,57,93,100,85,Feuer,Feuer
127,PINSIR,65,125,100,85,55,70,Käfer,Käfer
128,TAUROS,75,100,95,110,40,70,Normal,Normal
129,KARPADOR,20,10,55,80,15,20,Wasser,Wasser
130,GARADOS,95,125,79,81,60,100,Wasser,Flug
131,LAPRAS,130,85,80,60,85,95,Wasser,Eis
132,DITTO,48,48,48,48,48,48,Normal,Normal
133,EVOLI,55,55,50,55,45,65,Normal,Normal
134,AQUANA,130,65,60,65,110,95,Wasser,Wasser
135,BLITZA,65,65,60,130,110,95,Elektro,Elektro
136,FLAMARA,65,130,60,65,95,110,Feuer,Feuer
137,PORYGON,65,60,70,40,85,75,Normal,Normal
138,AMONITAS,35,40,100,35,90,55,Gestein,Wasser
139,AMOROSO,70,60,125,55,115,70,Gestein,Wasser
140,KABUTO,30,80,90,55,55,45,Gestein,Wasser
141,KABUTOPS,60,115,105,80,65,70,Gestein,Wasser
142,AERODACTYL,80,105,65,130,60,75,Gestein,Flug
143,RELAXO,160,110,65,30,65,110,Normal,Normal
144,ARKTOS,90,85,100,85,95,125,Eis,Flug
145,ZAPDOS,90,90,85,100,125,90,Elektro,Flug
146,LAVADOS,90,100,90,90,125,85,Feuer,Flug
147,DRATINI,41,64,45,50,50,50,Drache,Drache
148,DRAGONIR,61,84,65,70,70,70,Drache,Drache
149,DRAGORAN,91,134,95,80,100,100,Drache,Flug
150,MEWTU,106,110,90,130,154,90,Psycho,Psycho
151,MEW,100,100,100,100,100,100,Psycho,Psycho