### Import ⬇️

In [2]:
import pandas as pd

### CSV einlesen ⬇️

In [3]:
df_pokemon = pd.read_csv("../data/pokemon.csv", index_col="id")
df_moves = pd.read_csv("../data/moves.csv", index_col="move_id")

### Testanzeige ⬇️

In [4]:
df_pokemon

,name,hp,angriff,verteidigung,speed,sp_angriff,sp_verteidigung,typ1,typ2
id,,,,,,,,,
1,BISASAM,45,49,49,45,65,65,Gras,Gift
2,BISAKNOSP,60,62,63,60,80,80,Gras,Gift
3,BISAFLOR,80,82,83,80,100,100,Gras,Gift
4,GLUMANDA,39,52,43,65,60,50,Feuer,Feuer
5,GLUTEXO,58,64,58,80,80,65,Feuer,Feuer
...,...,...,...,...,...,...,...,...,...
147,DRATINI,41,64,45,50,50,50,Drache,Drache
148,DRAGONIR,61,84,65,70,70,70,Drache,Drache
149,DRAGORAN,91,134,95,80,100,100,Drache,Flug
150,MEWTU,106,110,90,130,154,90,Psycho,Psycho
151,MEW,100,100,100,100,100,100,Psycho,Psycho

In [5]:
df_moves

            move_name  effekt  staerke     typ  genauigkeit  pp
move_id
1               PFUND       0       40  Normal          100  35
2        KARATESCHLAG      43       50   Kampf          100  25
3          DUPLEXHIEB      29       15  Normal           85  10
4         KOMETENHIEB      29       18  Normal           85  15
5            MEGAHIEB       0       80  Normal           85  20
...               ...     ...      ...     ...          ...  ..
161         TRIPLETTE      36       80  Normal          100  10
162         SUPERZAHN      40        1  Normal           90  10
163         SCHLITZER      43       70  Normal          100  20
164         DELEGATOR      79        0  Normal            0  10
165       VERZWEIFLER      48       50  Normal          100   1

[165 rows x 6 columns]

### Fehlende oder fehlerhafte Werte identifizieren ⬇️

In [6]:
df_pokemon.isnull().sum()

name               0
hp                 0
angriff            0
verteidigung       0
speed              0
sp_angriff         0
sp_verteidigung    0
typ1               0
typ2               0
dtype: int64

In [7]:
df_moves.isnull().sum()

move_name      0
effekt         0
staerke        0
typ            0
genauigkeit    0
pp             0
dtype: int64

In [8]:
df_pokemon.info()

<class 'pandas.core.frame.DataFrame'>
Index: 151 entries, 1 to 151
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             151 non-null    object
 1   hp               151 non-null    int64
 2   angriff          151 non-null    int64
 3   verteidigung     151 non-null    int64
 4   speed            151 non-null    int64
 5   sp_angriff       151 non-null    int64
 6   sp_verteidigung  151 non-null    int64
 7   typ1             151 non-null    object
 8   typ2             151 non-null    object
dtypes: int64(6), object(3)
memory usage: 11.8+ KB

In [9]:
df_moves.info()

<class 'pandas.core.frame.DataFrame'>
Index: 165 entries, 1 to 165
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   move_name    165 non-null    object
 1   effekt       165 non-null    int64
 2   staerke      165 non-null    int64
 3   typ          165 non-null    object
 4   genauigkeit  165 non-null    int64
 5   pp           165 non-null    int64
dtypes: int64(4), object(2)
memory usage: 9.0+ KB

### Keine fehlenden oder fehlerhafte Werte gefunden
### Jetzt Typ-Bereinigung
### Welche Pokemon haben Typ1 == Typ2 ? ⬇️

In [11]:
gleiche_typen = df_pokemon[df_pokemon["typ1"] == df_pokemon["typ2"]]
print(f"Pokemon mit nur einem Typ: {len(gleiche_typen)}")
gleiche_typen

Pokemon mit nur einem Typ: 87

,name,hp,angriff,verteidigung,speed,sp_angriff,sp_verteidigung,typ1,typ2
id,,,,,,,,,
4,GLUMANDA,39,52,43,65,60,50,Feuer,Feuer
5,GLUTEXO,58,64,58,80,80,65,Feuer,Feuer
7,SCHIGGY,44,48,65,43,50,64,Wasser,Wasser
8,SCHILLOK,59,63,80,58,65,80,Wasser,Wasser
9,TURTOK,79,83,100,78,85,105,Wasser,Wasser
...,...,...,...,...,...,...,...,...,...
143,RELAXO,160,110,65,30,65,110,Normal,Normal
147,DRATINI,41,64,45,50,50,50,Drache,Drache
148,DRAGONIR,61,84,65,70,70,70,Drache,Drache
150,MEWTU,106,110,90,130,154,90,Psycho,Psycho
151,MEW,100,100,100,100,100,100,Psycho,Psycho

### Ausgabe mit len zeigt 87 x Typ1 == Typ2
### Ausgabe mit Variable "gleiche_typen" zeigt jedoch 86 unique Values an
### Test welches evtl. doppelt ist ⬇️

In [12]:
print(gleiche_typen[gleiche_typen.duplicated(subset="name", keep=False)][["name", "typ1", "typ2"]])

        name  typ1  typ2
id
29  NIDORAN?  Gift  Gift
32  NIDORAN?  Gift  Gift

### Nidoran männlich und weiblich haben normalerweise Geschlechtszeichen neben dem Namen https://www.bisafans.de/pokedex/029.php#attacken https://www.bisafans.de/pokedex/032.php
### Passe Nidoran mit W und M an ⬇️

In [13]:
df_pokemon.loc[df_pokemon.index == 29, "name"] = "NIDORAN_W"
df_pokemon.loc[df_pokemon.index == 32, "name"] = "NIDORAN_M"

In [15]:
df_pokemon.loc[[29, 32], ["name", "typ1", "typ2"]]

         name  typ1  typ2
id
29  NIDORAN_W  Gift  Gift
32  NIDORAN_M  Gift  Gift

### Nidoran männlich und weiblich Namen angepasst
### Kurzer Check ⬇️

In [21]:
gleiche_typen_neu = df_pokemon[df_pokemon["typ1"] == df_pokemon["typ2"]]

duplikate = gleiche_typen_neu[gleiche_typen_neu.duplicated(subset="name", keep=False)]

print(gleiche_typen_neu[gleiche_typen_neu.duplicated(subset="name", keep=False)][["name", "typ1", "typ2"]])

Empty DataFrame
Columns: [name, typ1, typ2]
Index: []

### Als nächstes Typ1 == Typ2 anpassen
### Wenn Typ1 == Typ2 dann Typ2 auf None setzen ⬇️

In [22]:
df_pokemon.loc[df_pokemon["typ1"] == df_pokemon["typ2"], "typ2"] = None

In [24]:
print(f"Pokemon mit zwei Typen: {df_pokemon['typ2'].notna().sum()}")
print(f"Pokemon mit einem Typ:  {df_pokemon['typ2'].isna().sum()}")

Pokemon mit zwei Typen: 64
Pokemon mit einem Typ:  87

### Ausgabe: Pokemon mit einem Typ 87 passt
### Jetzt unbekannte Typen bei den Moves bereinigen ⬇️

In [25]:
unbekannte_moves = df_moves[df_moves["typ"].str.contains("Unbekannt")]
print(f"Moves mit unbekanntem Typ: {len(unbekannte_moves)}")
print(unbekannte_moves[["move_name", "typ", "staerke"]])

Moves mit unbekanntem Typ: 0
Empty DataFrame
Columns: [move_name, typ, staerke]
Index: []

### Keine unbekannten Moves mehr?
### Weiterer Test ⬇️

In [26]:
df_moves[df_moves["staerke"] == 0]["typ"].value_counts()

typ
Normal     29
Psycho     10
Gras        4
Gift        4
Eis         2
Boden       1
Käfer       1
Elektro     1
Geist       1
Wasser      1
Flug        1
Name: count, dtype: int64

### Keine unbekannten Typen mehr – alles sauber! Die Status-Moves haben alle gültige Typen
### Bei neu Inititalisierung in 01_extraktion nach Neustart korrekt eingelesen worden
### Jetzt weiter mit Duplikate festestellen ⬇️

In [27]:
print(f"Pokémon Duplikate: {df_pokemon.duplicated().sum()}")
print(f"Moves Duplikate:   {df_moves.duplicated().sum()}")

Pokémon Duplikate: 0
Moves Duplikate:   0

### Perfekt, keine Duplikate!
### Jetzt bereinigtes Dataset speichern ⬇️

In [28]:
df_pokemon.to_csv("../data/pokemon_bereinigt.csv")
df_moves.to_csv("../data/moves_bereinigt.csv")

### CSV anzeigen

In [29]:
df_pokemon = pd.read_csv("../data/pokemon_bereinigt.csv", index_col="id")
df_moves = pd.read_csv("../data/moves_bereinigt.csv", index_col="move_id")

In [30]:
df_pokemon

,name,hp,angriff,verteidigung,speed,sp_angriff,sp_verteidigung,typ1,typ2
id,,,,,,,,,
1,BISASAM,45,49,49,45,65,65,Gras,Gift
2,BISAKNOSP,60,62,63,60,80,80,Gras,Gift
3,BISAFLOR,80,82,83,80,100,100,Gras,Gift
4,GLUMANDA,39,52,43,65,60,50,Feuer,NaN
5,GLUTEXO,58,64,58,80,80,65,Feuer,NaN
...,...,...,...,...,...,...,...,...,...
147,DRATINI,41,64,45,50,50,50,Drache,NaN
148,DRAGONIR,61,84,65,70,70,70,Drache,NaN
149,DRAGORAN,91,134,95,80,100,100,Drache,Flug
150,MEWTU,106,110,90,130,154,90,Psycho,NaN
151,MEW,100,100,100,100,100,100,Psycho,NaN

In [31]:
df_moves

            move_name  effekt  staerke     typ  genauigkeit  pp
move_id
1               PFUND       0       40  Normal          100  35
2        KARATESCHLAG      43       50   Kampf          100  25
3          DUPLEXHIEB      29       15  Normal           85  10
4         KOMETENHIEB      29       18  Normal           85  15
5            MEGAHIEB       0       80  Normal           85  20
...               ...     ...      ...     ...          ...  ..
161         TRIPLETTE      36       80  Normal          100  10
162         SUPERZAHN      40        1  Normal           90  10
163         SCHLITZER      43       70  Normal          100  20
164         DELEGATOR      79        0  Normal            0  10
165       VERZWEIFLER      48       50  Normal          100   1

[165 rows x 6 columns]